// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chrhglnpzftkqruygtie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocmhnbG5wemZ0a3FydXlndGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTYzODUsImV4cCI6MjA3MDM5MjM4NX0.NhsF9depHuFM37XBDkongqnTSjIoLZbJnZXwpCvr4Wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});